
from enum import Enum


class CaseState(str, Enum):

    RECEIVED = "RECEIVED"
    SCREENING = "SCREENING"
    DIAGNOSING = "DIAGNOSING"
    ELIGIBILITY_CHECK = "ELIGIBILITY_CHECK"
    DECISION = "DECISION"
    ACTION_PENDING = "ACTION_PENDING"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"


class CaseType(str, Enum):

    PAYMENT_FAILURE = "PAYMENT_FAILURE"
    CHECKOUT_ABANDONMENT = "CHECKOUT_ABANDONMENT"


class EventType(str, Enum):

    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_AUTHORIZED = "PAYMENT_AUTHORIZED"
    PAYMENT_CAPTURED = "PAYMENT_CAPTURED"
    ORDER_PAID = "ORDER_PAID"


class ProcessingStatus(str, Enum):

    RECEIVED = "RECEIVED"
    PROCESSED = "PROCESSED"
    DUPLICATE = "DUPLICATE"
    FAILED = "FAILED"


class RecoveryAction(str, Enum):

    RETRY = "RETRY"
    SEND_RECOVERY_REMINDER = "SEND_RECOVERY_REMINDER"
    SEND_RECOVERY_LINK = "SEND_RECOVERY_LINK"
    SUGGEST_ALTERNATIVE_PAYMENT_METHOD = "SUGGEST_ALTERNATIVE_PAYMENT_METHOD"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    STOP = "STOP"


class PolicyVerdictType(str, Enum):

    ALLOW = "ALLOW"
    DENY = "DENY"
    FORCE_ACTION = "FORCE_ACTION"


class RiskLevel(str, Enum):

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ProviderMode(str, Enum):

    RAZORPAY_TEST_MODE = "RAZORPAY_TEST_MODE"
    SIMULATION_MODE = "SIMULATION_MODE"


class HumanReviewDecision(str, Enum):

    APPROVE = "APPROVE"
    REJECT = "REJECT"
    OVERRIDE = "OVERRIDE"


class VerificationOutcome(str, Enum):

    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    STILL_PENDING = "STILL_PENDING"
    ESCALATED = "ESCALATED"
    ERROR = "ERROR"
